title: The Creative Dungeon
# description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://thecreativedungeon.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

# social:
#    github: brianmaierjr
#    twitter: brianmaierjr
#    facebook: brianmaierjr
#    email: brimaidesigns@gmail.com

# google_analytics: "UA-58263416-1"
